# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  compile: false
  cache_manifest: false
  source_path: client
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs



development:
  <<: *default
  # generated files for development, in /public/webpack/development
  public_output_path: webpack/development

  dev_server:
    host: localhost
    port: 3035
    hmr: true

test:
  <<: *default
  # generated files for test, in /public/webpack/test
  public_output_path: webpack/test

production:
  <<: *default
  # generated files for production, in /public/webpack/production
  public_output_path: webpack/production
  cache_manifest: true
