# Note: Base output directory of /public is assumed for static files
default: &default
  # Critical to set compile as false for React on Rails projects
  compile: false
  # Cache manifest.json for performance
  cache_manifest: false
  # souce_path is unused if using a custom configuration
  source_path: client

development:
  <<: *default
  # generated files for development, in /public/webpack/development
  public_output_path: webpack/development

  dev_server:
    host: localhost
    port: 3035
    hmr: true

test:
  <<: *default
  # generated files for test, in /public/webpack/test
  public_output_path: webpack/test

production:
  <<: *default
  # generated files for production, in /public/webpack/production
  public_output_path: webpack/production
  cache_manifest: true











# # Note: You must restart bin/webpack-dev-server for changes to take effect

# default: &default
#   source_path: client
#   source_entry_path: packs
#   public_output_path: packs
#   cache_path: tmp/cache/webpacker

#   # Additional paths webpack should lookup modules
#   # ['app/assets', 'engine/foo/app/assets']
#   resolved_paths: []

#   # Reload manifest.json on all requests so we reload latest compiled packs
#   cache_manifest: false

#   extensions:
#     - .jsx
#     - .js
#     - .sass
#     - .scss
#     - .css
#     - .module.sass
#     - .module.scss
#     - .module.css
#     - .png
#     - .svg
#     - .gif
#     - .jpeg
#     - .jpg

# development:
#   <<: *default
#   compile: true

#   # Reference: https://webpack.js.org/configuration/dev-server/
#   dev_server:
#     https: false
#     host: localhost
#     port: 3035
#     public: localhost:3035
#     hmr: false
#     # Inline should be set to true if using HMR
#     inline: true
#     overlay: true
#     compress: true
#     disable_host_check: true
#     use_local_ip: false
#     quiet: false
#     headers:
#       'Access-Control-Allow-Origin': '*'
#     watch_options:
#       ignored: /node_modules/


# test:
#   <<: *default
#   compile: true

#   # Compile test packs to a separate directory
#   public_output_path: packs-test

# production:
#   <<: *default

#   # Production depends on precompilation of packs prior to booting for performance.
#   compile: false

#   # Cache manifest.json for performance
#   cache_manifest: true
